### ISSUE TITLE
Enabling Ingress results in Error

### ISSUE THREAD

**Issue by pandalec** [owncloud-docker/helm-charts#19]
Hey! If I enable ingress in the helm chart I get the following error:

```
Error: INSTALLATION FAILED: YAML parse error on owncloud/templates/ingress.yaml: error converting YAML to JSON: yaml: line 17: mapping values are not allowed in this context
```

yaml looks like this:

```
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - secretName: owncloud-tls
      hosts:
         - owncloud.domain.com
```
