### ISSUE TITLE
Missing cronjob call for /usr/lib/php/sessionclean

### ISSUE THREAD

**Issue by astromechza** [owncloud-docker/helm-charts#66]
I found that my /mnt/data/sessions directory was filling up with old session files. up to 80k of them without any cleanup.

There's a crontab entry for it in cron.d, but that doesn't get called by anything, and not by the `occ system:cron` background jobs either.

I solved this myself by adding a manual `cronjob` like below, but ideally we'd include this in the helm chart or make sure the existing helm chart calls it after running the owncloud `/usr/bin/cronjob` file.

```
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: owncloud-phpsessionclean
  namespace: production
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: cronjob
            image: docker.io/owncloud/server:10.13.3
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "/usr/lib/php/sessionclean"]
            envFrom:
              - configMapRef:
                  name: owncloud-env-config
            volumeMounts:
              - name: owncloud-data
                mountPath: /mnt/data
              - name: config-volume
                mountPath: /mnt/data/config/configmap.config.php
                subPath: configmap.config.php
          volumes:
            - name: owncloud-data
              persistentVolumeClaim:
                claimName: owncloud
            - name: config-volume
              secret:
                secretName: owncloud-config
```
