### ISSUE TITLE
Ingress Class in Values.yaml wrong

### ISSUE THREAD

**Issue by PeeK1e** [owncloud-docker/helm-charts#79]
Theres is an discrepancy in the ingress template and the values yaml for the ingress class name

`templates/ingress.yaml`:
```
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
```
`values.yaml`:
```
ingress:
  # -- Enables the Ingress.
  enabled: false
  # -- Ingress class to use.
  # Uses the default ingress class if not set.
  ingressClassName: ""
```

`{{- with .Values.ingress.className }}` should be `{{- with .Values.ingress.ingressClassName }}`

It's up to you to fix the naming but it should be correct :P
(The readme is also incorrect)
